name: "Setup Dev Drive"
description: "A GitHub Action to setup a Windows Dev Drive."
author: "samypr100"
branding:
  icon: hard-drive
  color: purple
inputs:
  drive-size:
    description: "Drive Size. Examples: 1GB, 3GB, 10GB."
    default: "1GB"
  drive-format:
    description: "Drive Format. Examples: FAT, FAT32, exFAT, NTFS, ReFS."
    default: "ReFS"
  drive-path:
    description: "Absolute or relative path to the Dev Drive storage location. Example: C:/path/to/my/dev_drive.vhdx"
    default: "dev_drive.vhdx"
  drive-type:
    description: "Determines whether all space is allocated initially or over time. Example: Fixed or Dynamic."
    default: "Dynamic"
  mount-path:
    description: "Specific mount location for the Dev Drive. Only compatible with NTFS or ReFS."
    required: false
  mount-if-exists:
    description: "Supports mounting an existing VHDX located in `drive-path`, avoiding creation overhead."
    default: "false"
  workspace-copy:
    description: "Copy your GITHUB_WORKSPACE checkout to your Dev Drive. Examples: true, false."
    default: "false"
  native-dev-drive:
    description: "Use native dev drive support when available."
    default: "true"
  env-mapping:
    description: "Allows mapping environment variables generated by this action to new user-defined ones."
    required: false
runs:
  using: "node20"
  main: "dist/setup/index.js"
  post: "dist/cleanup/index.js"
